### ISSUE TITLE
Add url link to study

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/spa-study#45]
https://johnpapa.net/pageinspa/

via @jrhorn424

**Comment by RealWeeks** [comment]
@berziiii added in commit bd1dff8.  Please close? ![bitmoji](https://render.bitstrips.com/v2/cpanel/9666156-136432832_1-s4-v1.png?transparent=1&width=246)

**Comment by RealWeeks** [comment]
via slack: "Brian Berzellini [9:51 AM]  
Good to close! Love he emoji"
